### PR TITLE
Add checkout token to support private repos

### PR DESCRIPTION
**Pull request by szinn**
Flux-diff is not able to pull the repo if it is a private repo. Adding a token to the checkout action appears to resolve that issue.

### CODE REVIEW

**Comment by allenporter** [comment]
I may need to run the github workflow at an older version. Let me work on that to fix CI.

**Comment by szinn** [comment]
I wonder if this is a log in to gh?

**Comment by allenporter** [comment]
I'm not really understanding the action failures here. Are they a result of this change?

**Review by allenporter — CHANGES_REQUESTED** [review]
Do the tests pass with the default value unset?

**Comment by tyriis** [comment]
@szinn @allenporter, what needs to be done to fix this? (when setting the default to '') it works for me, I have opened a pr, but looks like there is an issue with the test setup.

**Comment by yalait** [comment]
Right here fix problems
https://github.com/szinn/flux-local/pull/2

**Review by allenporter — APPROVED** [review]
I resolved the merge conflict and re-ran the tests and things look good.

**Pull request merged**
